FROM python:3.13-slim-bookworm

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.10.4 /uv /uvx /bin/

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY src ./src

RUN python3 run_codegen.py
EXPOSE 50051

CMD ["uv", "run", "python", "-m", "src.grpc_api"]
